package ByteBot;

import GoogleSearch.GoogleForm;
import MusicPlayer.mp3Player;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;

/**
 * 
 * This class will serve as the Main Frame of the chat bot.
 * @author Bugay, Maglinao, Mariano, Olivar, Robles, Susara
 * @since 2019-03-28
 * @version 1.0
 */
public class ChatBotMainFrame extends javax.swing.JFrame {
    public DefaultListModel listModel = new DefaultListModel();
    public int lineLimit = 0;
    public int localCount = 0;
    
    /**
     * Constructor.
     * Creates new form ChatBotMainFrame
     * Initializes components
     */
    public ChatBotMainFrame() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(16, 122, 169));
        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 150, 60));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 520, 60));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));

        jList1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jList1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jList1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 680, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ByteBot/mainFrame.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * This method performs action to start the conversation that is displayed on JList.
    * @param evt button clicking will run the jButtonActionPerformed method.
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChatBotBrain ChatBot = new ChatBotBrain();
        
        if (lineLimit == 5){
            listModel.clear();
            lineLimit = 0;
        }
        if(jTextField1.getText().toLowerCase().contains("exit")){
            closing();
        }
        else if(jTextField1.getText().toLowerCase().contains("music")){
            mp3Player player = new mp3Player();
            listModel.addElement("......Music Player Software Initialized:");
            player.setVisible(true);
            jList1.setModel(listModel);
            
            lineLimit +=1;
            jTextField1.setText("");
        }
        else if(jTextField1.getText().toLowerCase().contains("search")){
            GoogleForm googleForm = new GoogleForm();
            listModel.addElement("......Google Search Engine Initialized:");
            jList1.setModel(listModel);
            googleForm.setVisible(true);
            lineLimit +=1;
            jTextField1.setText("");
        }
        else if(jTextField1.getText().toLowerCase().contains("draw") || jTextField1.getText().toLowerCase().contains("write") ){
            listModel.addElement("......Benbox Drawing Software Initialized:");
            jList1.setModel(listModel);
            ChatBotBrain.draw();
            lineLimit +=1;
            jTextField1.setText("");
        }
        else if(jTextField1.getText().toLowerCase().contains("learn")){
            Voice voice;
            VoiceManager voiceManager = VoiceManager.getInstance();
            voice = voiceManager.getVoice(ChatBotBrain.VOICENAME);
        
            voice.allocate();
        
            try{
                voice.speak("What do you want me to learn?");
            }
            catch(Exception e){
        }
            listModel.addElement("ME: " + jTextField1.getText());
            listModel.addElement("BYTEBOT: What do you want me to learn?");
            jList1.setModel(listModel);
            jTextField1.setText("");
            lineLimit +=1;
            localCount = 1;
        }
        else if (localCount == 1){
            listModel.addElement("ME: " + jTextField1.getText());
            listModel.addElement("BYTEBOT: " + ChatBot.learn(jTextField1.getText()));
            jList1.setModel(listModel);
            jTextField1.setText("");
            lineLimit +=1;
            localCount = 2;
        }
        else if (localCount == 2){
            listModel.addElement("ME: " + jTextField1.getText());
            listModel.addElement("BYTEBOT: " + ChatBot.response(jTextField1.getText()));
            jList1.setModel(listModel);
            jTextField1.setText("");
            lineLimit +=1;
            localCount = 0;
        }
        else if(localCount == 0){
        listModel.addElement("ME: " + jTextField1.getText());
        listModel.addElement("BYTEBOT: " + ChatBot.analyzeChat(jTextField1.getText()));
        jList1.setModel(listModel);
        jTextField1.setText("");
        lineLimit +=1;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * This method allows the user to send message to the chat bot by the use of the ENTER key.
    */
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            jButton1.doClick();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatBotMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatBotMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatBotMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatBotMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatBotMainFrame().setVisible(true);
            }
        });
    }
    
    /**
    * This method closes the ChatBotMainFrame.
    */
    private void closing(){
        WindowEvent w = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
